// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnkZ8fq0i5MaeSSIG0iL-m45SEl5vGrsw',
    appId: '1:682853037893:web:5df9c6f76245768bfbf02c',
    messagingSenderId: '682853037893',
    projectId: 'sara-e2730',
    authDomain: 'sara-e2730.firebaseapp.com',
    storageBucket: 'sara-e2730.appspot.com',
    measurementId: 'G-RC0N915T22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKtZJ9OCr10hgwFJRM_9yW3VZtIReAT2k',
    appId: '1:682853037893:android:c6edd7e4c961c746fbf02c',
    messagingSenderId: '682853037893',
    projectId: 'sara-e2730',
    storageBucket: 'sara-e2730.appspot.com',
  );
}


